//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceSystem.RequestDetails
{


	public partial class ProfileControl
	{

		/// <summary>
		/// UserSummary control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::AdvanceSystem.RequestDetails.UserSummary UserSummary;

		/// <summary>
		/// Pie_Balance control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::AdvanceSystem.RequestDetails.Pie_Balance Pie_Balance;

		/// <summary>
		/// D_ChartWithNulls control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::AdvanceSystem.RequestDetails._3D_ChartWithNulls D_ChartWithNulls;

		/// <summary>
		/// CompletionSummary control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::AdvanceSystem.RequestDetails.CompletionSummary CompletionSummary;

		/// <summary>
		/// OutstandingAdvance control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::AdvanceSystem.RequestDetails.OutstandingAdvance OutstandingAdvance;

		/// <summary>
		/// History control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::AdvanceSystem.RequestDetails.History History;
	}
}
